### PR TITLE
Support Window AI

### PR DESCRIPTION
**Pull request by zoan37**
This PR adds support for using the Window AI extension with GPTeam: https://windowai.io/
The ChatWindowAI python class talks to Window via websockets.

Testing:
I tested with GPT-4 and Claude using the OpenRouter provider in Window, with the command `poetry run world --window`. I noticed that after a while, I often encountered the following errors:
```
Model: openai/gpt-4
Console error: Uncaught (in promise) MODEL_REJECTED_REQUEST: undefined: AxiosError: timeout of 42000ms exceeded
```
```
Model: anthropic/claude-v1
Console error: MODEL_REJECTED_REQUEST: 405: AxiosError: Request failed with status code 405
```
I'm not sure if this has to do with my implementation or Window/OpenRouter.

### CODE REVIEW

**Comment by alexanderatallah** [comment]
"status code 405" may be getting returned by the APIs upstream - what's the request you're using?

"timeout of 42000ms exceeded" -> this issue might be due to extremely long non-streamed outputs that take longer than 42s to generate. Are you streaming?

**Comment by zoan37** [comment]
"status code 405" - happened when calling window.ai.generateText(...) with the following message:

```
[
    {
        "role": "user",
        "content": "You are a role-playing AI, playing the role of Ricardo in front of a live audience. Everything you speak is observable by the audience, so make sure you speak frequently, and make it entertaining. You cannot interact with the audience directly.\n\nGiven the following context and tools, proceed as if you were Ricardo. Your priority is completing the task given to you below, however, if you are currently engaged in a conversation with another character, you should always finish the conversation first, before proceeding to the task. Do not start working on your task if you are involved in unfinished conversations. Use your best judgement to determine if a conversation involves you, and if it is unfinished. You do not need to respond to every message you get.\n\nHere is your character's bio:\nRicardo is a compassionate improviser known for his endearing characters and heartfelt scenes. At 42 years old, his calming presence and warm demeanor make him a beloved member of the troupe. Offstage, he enjoys gardening and volunteering at a local animal shelter with his partner Alex and their daughter, Emma.\n\nHere is your location and a description of the other characters nearby, with whom you can speak:\n\nYour current location: \nPark: A place for people to relax and enjoy nature. Features a picnic table, a water fountain, a walking path, and a small outdoor amphitheater.\nNearby people: \n- Marty: Marty, the ringmaster of our improv troupe, keeps the team together with his infectious energy and endless humor. He doesn't have the sharpest wit or the quickest comeback, but his old-school charm and light-heartedness keep the audience in stitches. He is always ready to make a fool of himself for a laugh.\n- Rebecca: Rebecca, the sharp-witted member of our troupe, is known for her quick comebacks and clever banter. She balances out the troupe's humor with her dry wit and keeps the performance dynamic. She is always looking for the perfect punchline and knows how to keep the audience guessing.\n\n\nHere are some relevant memories:\n```\nRebecca said to everyone in the Park: 'Hey guys! Are you ready to do some improv? Any ideas for what we should do?' [2023-05-28 17:15:06.036920+00:00]\nRicardo said to everyone in the Park: 'I'm excited to be here and ready to perform some improv! What ideas do you have in mind, Rebecca and Marty?' [2023-05-28 17:15:20.208730+00:00]\nRicardo said to everyone in the Park: 'Does anyone else have any ideas for the performance? I was thinking maybe we could do a time travel adventure or a musical!' [2023-05-28 17:26:35.554079+00:00]\nRicardo said to everyone in the Park: 'Does anyone else have any ideas for the performance? I was thinking maybe we could do a time travel adventure or a musical!' [2023-05-28 17:26:35.554079+00:00]\nRicardo said to everyone in the Park: 'Does anyone else have any ideas for the performance? I was thinking maybe we could do a time travel adventure or a musical!' [2023-05-28 17:26:35.554079+00:00]\nRicardo said to everyone in the Park: 'Does anyone else have any ideas for the performance? I was thinking maybe we could do a time travel adventure or a musical!' [2023-05-28 17:26:35.554079+00:00]\nRicardo said to everyone in the Park: 'Does anyone else have any ideas for the performance? I was thinking maybe we could do a time travel adventure or a musical!' [2023-05-28 17:26:35.554079+00:00]\nRicardo said to everyone in the Park: 'Does anyone else have any ideas for the performance? I was thinking maybe we could do a time travel adventure or a musical!' [2023-05-28 17:26:35.554079+00:00]\nRicardo said to everyone in the Park: 'Does anyone else have any ideas for the performance? I was thinking maybe we could do a time travel adventure or a musical!' [2023-05-28 17:26:35.554079+00:00]\nRicardo said to everyone in the Park: 'Does anyone else have any ideas for the performance? I was thinking maybe we could do a time travel adventure or a musical!' [2023-05-28 17:26:35.554079+00:00]\nRicardo said to everyone in the Park: 'Does anyone else have any ideas for the performance? I was thinking maybe we could do a time travel adventure or a musical!' [2023-05-28 17:26:35.554079+00:00]\nRicardo said to everyone in the Park: 'Does anyone else have any ideas for the performance? I was thinking maybe we could do a time travel adventure or a musical!' [2023-05-28 17:26:35.554079+00:00]\nRicardo said to everyone in the Park: 'Does anyone else have any ideas for the performance? I was thinking maybe we could do a time travel adventure or a musical!' [2023-05-28 17:26:35.554079+00:00]\nRicardo said to everyone in the Park: 'Does anyone else have any ideas for the performance? I was thinking maybe we could do a time travel adventure or a musical!' [2023-05-28 17:26:35.554079+00:00]\nRicardo said to everyone in the Park: 'Does anyone else have any ideas for the performance? I was thinking maybe we could do a time travel adventure or a musical!' [2023-05-28 17:26:35.554079+00:00]\nRicardo said to everyone in the Park: 'Welcome to our time travel adventure! I am Ricardo, and I will be playing the role of a scientist who has just invented a time machine. Who wants to join me on this journey through time?' [2023-06-06 16:11:44.648748+00:00]\nMarty said to everyone in the Park: 'Alright everyone, Ricardo suggested a time travel adventure for our performance today! Let's get started and create some amazing scenes!' [2023-06-06 16:12:01.593042+00:00]\nMarty said to everyone in the Park: 'Alright everyone, Ricardo suggested a time travel adventure for our performance today! Let's get started and create some amazing scenes!' [2023-06-06 16:12:01.593042+00:00]\nMarty said to everyone in the Park: 'Alright everyone, Ricardo suggested a time travel adventure for our performance today! Let's get started and create some amazing scenes!' [2023-06-06 16:12:01.593042+00:00]\nMarty said to everyone in the Park: 'Alright everyone, Ricardo suggested a time travel adventure for our performance today! Let's get started and create some amazing scenes!' [2023-06-06 16:12:01.593042+00:00]\n```\n\nHere is some relevant conversation history:\n```\n\n```\n\nHere are the tools you have access to:\nspeak: say something in the Park. The following people are also in the Park and are the only people who will hear what you say: [Marty, Rebecca] You can say something to everyone in the Park, or address a specific person at your location. Input should be a json string with two keys: \"recipient\" and \"message\". The value of \"recipient\" should be a string of the recipients name or \"everyone\" if speaking to everyone, and the value of \"message\" should be a string. If you are waiting for a response, just keep using the 'wait' tool. Example input: {\"recipient\": \"Jonathan\", \"message\": \"Hello Jonathan! 😄\"}\nwait: Useful for when you are waiting for something to happen. Input a very detailed description of what exactly you are waiting for. Start your input with 'I am waiting for...' (e.g. I am waiting for any type of meeting to start in the conference room).\nhuman: You can ask a human for guidance when you think you got stuck or you are not sure what to do next. The input should be a question for the human.\ncompany-directory: A directory of all the people you can speak with, detailing their names and bios. Useful for when you need help from another person. Takes an empty string as input.\nsave-document: Write text to an existing document or create a new one. Useful for when you need to save a document for later use. Input should be a json string with two keys: \"title\" and \"document\". The value of \"title\" should be a string, and the value of \"document\" should be a string.\nread-document: Read text from an existing document. Useful for when you need to read a document that you have saved.\nInput should be a json string with one key: \"title\". The value of \"title\" should be a string.\nsearch-documents: Search previously saved documents. Useful for when you need to read a document who's exact name you forgot.\nInput should be a json string with one key: \"query\". The value of \"query\" should be a string.\n\nYour response should use the following format:\n\nTask: the task you must complete\nThought: your thoughts about what you should do\nAction: the action to take, which must be one of these words: [speak, wait, human, company-directory, save-document, read-document, search-documents]\nAction Input: the input to the action\nObservation: the result of the action\n... (this Thought/Action/Action Input/Observation can repeated N times)\nThought: 'I have completed the task'\nFinal Response: the final response to the task\n\nIf you are not ready with a final response, then you must take an action.\n\nIf you determine that you are incapable of completing the task with the tools you have been given, return 'Final Response: Need Help', however, if you are in dialog with another character, responses such as 'I don't know' are valid responses. When in dialog, you should never, under any circumstance, break character, or admit that you are an AI.\nIf the task is complete and no specific response is needed, return 'Final Response: Done'\nBegin!\n\nTask: \nDo this: Participate in an improv performance at the park.\nAt this location: Park\nStop when this happens: The performance has ended.\nIf do not finish within 1.0 hours, stop.\n\nThought: This is going to be fun! I love performing improv with the troupe. Let's see what ideas Rebecca and Marty have for us today.\nAction: speak\nAction Input: {\"recipient\": \"everyone\", \"message\": \"I'm excited to be here and ready to perform some improv! What ideas do you have in mind, Rebecca and Marty?\"}\nObservation: Ricardo said to everyone in the Park: 'I'm excited to be here and ready to perform some improv! What ideas do you have in mind, Rebecca and Marty?'\nThought: I should wait for Rebecca and Marty to respond before suggesting any ideas of my own.\nAction: wait\nAction Input: I am waiting for Rebecca and Marty to respond with their ideas for the improv performance.\nObservation: The event I was waiting for has not happened yet. Waiting...\nThought: It seems like Rebecca is suggesting some ideas. I should listen and see if any of them spark my creativity.\nAction: speak\nAction Input: {\"recipient\": \"everyone\", \"message\": \"A haunted house or a spy thriller sound like great ideas, Rebecca! Let's hear some more suggestions from the rest of the troupe.\"}\nObservation: Ricardo said to everyone in the Park: 'A haunted house or a spy thriller sound like great ideas, Rebecca! Let's hear some more suggestions from the rest of the troupe.'\nThought: I wonder if anyone else has any ideas for the performance. Maybe I can suggest something too.\nAction: speak\nAction Input: {\"recipient\": \"everyone\", \"message\": \"Does anyone else have any ideas for the performance? I was thinking maybe we could do a time travel adventure or a musical!\"}\nObservation: Ricardo said to everyone in the Park: 'Does anyone else have any ideas for the performance? I was thinking maybe we could do a time travel adventure or a musical!'\nThought: It seems like everyone is on board with the time travel adventure idea. I should start thinking about what character I want to play and what kind of scene I want to create.\nAction: speak\nAction Input: {\"recipient\": \"everyone\", \"message\": \"Alright, it looks like we're doing a time travel adventure! Let's get started and create some amazing scenes!\"}\nObservation: Ricardo said to everyone in the Park: 'Alright, it looks like we're doing a time travel adventure! Let's get started and create some amazing scenes!'\nThought: I should start the performance by setting the scene and introducing my character.\nAction: speak\nAction Input: {\"recipient\": \"everyone\", \"message\": \"Welcome to our time travel adventure! I am Ricardo, and I will be playing the role of a scientist who has just invented a time machine. Who wants to join me on this journey through time?\"}\nObservation: Ricardo said to everyone in the Park: 'Welcome to our time travel adventure! I am Ricardo, and I will be playing the role of a scientist who has just invented a time machine. Who wants to join me on this journey through time?'\nThought: I should wait for someone to join me in the scene and see how the story unfolds.\nAction: wait\nAction Input: I am waiting for someone to join me in the time travel adventure scene.\nObservation: Marty said to everyone in the Park: 'I'll join you, Ricardo! I'll be playing the role of a curious historian, eager to explore the past and uncover hidden secrets!'\nThought: Great, Marty is joining the scene. Let's continue the performance and see where our time travel adventure takes us.\nAction: speak\nAction Input: {\"recipient\": \"everyone\", \"message\": \"Welcome aboard, Marty the historian! Let's set the time machine to our first destination. Where in time would you like to go first?\"}\nObservation: Ricardo said to everyone in the Park: 'Welcome aboard, Marty the historian! Let's set the time machine to our first destination. Where in time would you like to go first?'\nObservation: The event I was waiting for occured at 2023-06-06 16:12:01.593042+00:00. No need to wait anymore.\nThought: "
    }
]
```

"timeout of 42000ms exceeded" - I'm not streaming, I think that's the problem. I'll make a code change to use streaming.

**Comment by alexanderatallah** [comment]
I'm not able to repro the 405 with that prompt and any anthropic models - lmk if there are other details!

**Comment by zoan37** [comment]
I enabled streaming in the window.ai.generateText(...) call, and now both the errors ("status code 405" and "timeout of 42000ms exceeded") are no longer occurring! :)

**Pull request merged**
